### ISSUE TITLE
Raspberry pi pico variant?

### ISSUE THREAD

**Issue by jh0nny2k** [b1nc/Egg-On-Rice-Controller#1]
Hi,

Any chance you can modify the pcb to incorporate a raspberry pi pico also ? 

I would really like to make one for myself and basically i really really love your design. I already asked for pricing for the acrilic cutouts and i would like to order some pcb's.

Probably this would be beneficial for other people that also want to copy your design. Plus the brook boards are pretty expensive for the economy where i live in.

Kind regards,
Ionut

**Comment by b1nc** [comment]
Hi there,

Thanks for your interest in my design.

Yes, adding a Raspberry Pi Pico footprint should be no problem. I'll do some research on it and work it out, but I won't be home until later this month so it will have to be a bit for the PCB to be finished.

I've also been planning on revising the USB-C connector, changing it to a removable daughterboard of some sort so the main board itself will not suffer any damage if the USB-C connector was to be ripped off (happened to me once but it was probably due to sloppy soldering).

Please tell me what you think about that and some other changes you'd like to see.

Thank you,
b1nc

**Comment by jh0nny2k** [comment]
Thanks very much for taking a look at this.

When it's done it's done. Thank you for investing your time. Sounds good
about the usb type c connector.

I'll follow your project.

Kind regards,
Ionut
